name: kanagawa-ruins
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - geopandas
  - shapely
  - pyproj
  - rasterio
  - gdal
  - opencv
  - folium
  - matplotlib
  - requests
  - jupyterlab
  - pytest
  - pyogrio
  - pip
  - pip:
      - pyarrow==23.0.1
      - duckdb==1.4.3
      - osmium==4.2.0
